# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#

title: EdgeBus Documentation
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The EdgeBus is an application level network edge bus that adds connectivity, auditability, and observability to your apps with no code changes.
baseurl: "/" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
## Select theme
theme: "just-the-docs"
##
permalink: pretty


# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logo.webp"

compress_html:
  ignore:
    envs: all

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false


mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.4.0"


# Aux links for the upper right navigation
aux_links:
  "See on GitHub":
    - "https://github.com/edgebus/edgebus"
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true


# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase


# Back to top link
back_to_top: true
back_to_top_text: "Back to top"


# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true


# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "Copyright &copy; 2021-2024 EdgeBus Labs</a>"


# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html


# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/edgebus/edgebus" # the github URL for your repo
gh_edit_branch: "docs" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately


# Color scheme supports "light" (default) and "dark"
color_scheme: light
# color_scheme: dark


# Configure a color and (optionally) title for each kind of callout you want to use, e.g.:
#
# {: .warning }
# A paragraph...
#
callouts:
  important:
    title: Important
    color: purple
  note:
    title: Note
    color: blue
  note-title:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red
  custom:
    color: pink
    opacity: 0.3
callouts_opacity: 0.3


# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: G-E60V5MFB80
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)


# # Define Jekyll collections
# collections:
#   # Define a collection named "development", its documents reside in the "_development" directory
#   development:
#     permalink: "/:collection/:path"
#     output: true
#   # Define a collection named "management", its documents reside in the "_management" directory
#   management:
#     permalink: "/:collection/:path"
#     output: true


plugins:
  - jemoji
